//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ex2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_ExamEntities : DbContext
    {

        public static DB_ExamEntities _context;

        public DB_ExamEntities()
            : base("name=DB_ExamEntities")
        {
        }

        public static DB_ExamEntities GetContext()
        {
            if (_context == null)
                _context = new DB_ExamEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Control_Employes> Control_Employes { get; set; }
        public virtual DbSet<Control_Tasks> Control_Tasks { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Grades> Grades { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
    }
}
